### ISSUE TITLE
Several wallpapers for Bing

### ISSUE THREAD

**Issue by ArtyIF** [swsnr/gnome-shell-extension-picture-of-the-day#27]
Bing can return up to 8 wallpapers for each day. This extension only lets you see the first one, while something like Windows 11 lets you switch between 4 of them. I'm aware that implementing a similar feature would require a lot of work that's only useful for a single source, but it can also be implemented by fetching a random image each refresh by randomizing the `idx` parameter in the query between 0 and 7.

**Comment by ArtyIF** [comment]
> I didn't know. Where does this info come from? Specifically, how do you know Bing serves eight images?

I found a repo with a third-party Bing Wallpaper REST API and it mentioning how it has an index parameter that can take values from 0 to 7. Also, you can change the `n` parameter for the official API to return several images at once. The limit is 8, after that it just returns 8 elements.

![image](https://github.com/swsnr/gnome-shell-extension-picture-of-the-day/assets/8017858/ecdc70a1-d384-4888-a9e2-491c2a53672d)

**Comment by swsnr** [comment]
Cool. I guess I'll make it cycle through all alternatives, but might take me a while to implement this 🙂
