### ISSUE TITLE
Option to hide panel icon

### ISSUE THREAD

**Issue by FelixFourcolor** [swsnr/gnome-shell-extension-picture-of-the-day#47]
This one:

![Screenshot from 2024-01-21 06-26-36](https://github.com/swsnr/gnome-shell-extension-picture-of-the-day/assets/34260584/c3a00d4c-db5c-407e-8429-6d2b98b36570)

Can you add an option in the extension preferences to hide it?

**Comment by swsnr** [comment]
Please do make a pull request. I have no use for this seeing, so I won't implement it myself.  I'm closing this because it's not actionable for me.
