### ISSUE TITLE
Allow selecting multiple sources

### ISSUE THREAD

**Issue by FelixFourcolor** [swsnr/gnome-shell-extension-picture-of-the-day#48]
Is it possible to let the user select multiple sources, including all of them?

**Comment by swsnr** [comment]
I'm not sure how this should work?

**Comment by FelixFourcolor** [comment]
The extension listens to multiple sources at once. When any of them gets a new image, it downloads it and sets it the desktop image.

Please excuse my colloquial description as I'm not a programmer and I'm not familiar with the technical details. But it seems to me something like that should be possible.

**Comment by swsnr** [comment]
I see. It's bit how this extension works tho, and in any case that's not something I need, so I don't think I'll add it myself.  Please do make a pull request if you like to; meanwhile I'm closing this because it's not actionable to me.
