### ISSUE TITLE
New Useful Feature

### ISSUE THREAD

**Issue by 2077DevWave** [swsnr/gnome-shell-extension-picture-of-the-day#67]
Please add a feature that changes the background image every X hours. I think this feature will be very useful and I would be really grateful if you add it. The image can be among the images already downloaded or a new request.

**Comment by swsnr** [comment]
I'm not sure how you figure this it'd work? I mean except for bing all these source only have one new picture per day?

In any case, I don't think I'd use this myself, so I don't think I'll add it it myself. Closing since it's not actionable to me.

Pull requests are always welcome 🙂
